package com.example.lottery_program

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import java.util.Random

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val result = findViewById<TextView>(R.id.results)
        val button = findViewById<Button>(R.id.button)
        val machineResult = findViewById<TextView>(R.id.machineResults)

        button.setOnClickListener {
            val humanOutput = humanCalculate(result)
            val machineOutput = machineCalculate(machineResult)

            if (humanOutput.containsAll(machineOutput)){
                val victoryMsg =findViewById<TextView>(R.id.victory)
                val victoryMessage = "You have won the Lottery!!!\nCongratulations you have won $10,000"
                victoryMsg.text = victoryMessage
            }

        }
    }

    fun humanCalculate(results: TextView): MutableList<Int>{
        val res = mutableListOf<Int>()

        val gen: Random = Random()
        var newNum = 1 + gen.nextInt(49)

        while (res.size < 6) {
            if (newNum !in res)
                res.add(newNum)
            else
                newNum = 1 + gen.nextInt(49)
        }
        results.setText(" ")

        val displayText = "Your lottery number: \n"

        results.text = displayText

        for (i in res) {
            results.append("" + i + " ")
        }
        return res
    }

    fun machineCalculate(mResults: TextView): MutableList<Int>{
        val res = mutableListOf<Int>()

        val gen: Random = Random()
        var newNum = 1 + gen.nextInt(49)

        while (res.size < 6) {
            if (newNum !in res)
                res.add(newNum)
            else
                newNum = 1 + gen.nextInt(49)
        }
        mResults.setText(" ")

        val displayText = "Lottery number generated by machine: \n"

        mResults.text = displayText

        for (i in res) {
            mResults.append("" + i + " ")
        }
        return res
    }
}